/** An item drop from a creep. */
export interface ItemDrop {
  type: itemtype;
  level: number;
}

/** A creep in a camp, with optional item drops. */
export interface CreepUnit {
  id: string;
  itemDrops?: ItemDrop[];
}

/** A single creep camp composition. */
export type CreepCamp = CreepUnit[];

/** Creep camp data extracted from WC3 1v1 Ladder Maps. */
export const CREEP_CAMPS: Record<string, CreepCamp[]> = {
  'Dalaran Ruins': [
    [{ id: 'nftr' }, { id: 'nogr' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwzr' }],
    [{ id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkot' }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nomg' }],
    [{ id: 'nmrl' }, { id: 'nmrr' }, { id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nftt' }],
    [{ id: 'nass' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg' }],
  ],
  'Lordaeron Summer': [
    [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrt' }],
    [{ id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nftr' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkot' }],
    [{ id: 'ntrs' }, { id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ngnw' }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nftr' }, { id: 'nftt' }],
    [{ id: 'nsc3', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nscb' }, { id: 'ntrt' }, { id: 'ntrt' }],
    [{ id: 'nftr' }, { id: 'nftr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }],
    [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nmrr' }, { id: 'nmrr' }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }],
    [{ id: 'nmrl' }, { id: 'nmrr' }, { id: 'nmrr' }, { id: 'nsc2', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }, { id: 'nmrr' }],
    [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nogm' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }],
    [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }],
    [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrm' }, { id: 'nmrr' }, { id: 'nmrr' }],
    [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }],
    [{ id: 'nmrr' }, { id: 'nmrr' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ntrt' }, { id: 'ntrt' }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftr' }, { id: 'nftr' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'ngno' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw' }],
    [{ id: 'nfsh' }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }],
    [{ id: 'nfsh' }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }],
    [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg' }],
    [{ id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrr' }, { id: 'nmrr' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkog' }, { id: 'nkot' }, { id: 'nkot' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }],
  ],
  'Lordaeron Winter': [
    [{ id: 'nftt' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }],
    [{ id: 'nfrs', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nwlt' }, { id: 'nwlt' }],
    [{ id: 'ngna' }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwlt' }],
    [{ id: 'nmam', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ntka' }, { id: 'ntkt' }],
    [{ id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntks' }, { id: 'ntkt' }],
    [{ id: 'ngnw' }, { id: 'nitr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntks' }, { id: 'ntks' }],
    [{ id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntkt' }, { id: 'ntkw' }],
    [{ id: 'nfsh' }, { id: 'nitt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nwwf' }],
    [{ id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nfrl' }, { id: 'nfsh' }, { id: 'nftb' }],
    [{ id: 'nitp' }, { id: 'nitt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nitt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nith' }, { id: 'nits' }, { id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nplg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nftb' }, { id: 'nitt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nplb' }],
    [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrr' }],
    [{ id: 'nitp' }, { id: 'nitr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntkt' }],
    [{ id: 'nfps' }, { id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nanb' }, { id: 'nanc' }, { id: 'nano', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nanw' }, { id: 'nnwl', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ngnw' }],
    [{ id: 'nith' }, { id: 'nitr' }, { id: 'nitr' }, { id: 'nits' }, { id: 'nitw', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }],
  ],
  'Northrend': [
    [{ id: 'nsts', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwlt' }, { id: 'nwlt' }],
    [{ id: 'nmrr' }, { id: 'nmtw' }, { id: 'nsel', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'ndth', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndtr' }, { id: 'ndtr' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'ndtt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nspb' }, { id: 'nspg' }],
    [{ id: 'ndtb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndtt' }, { id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nfrl' }],
    [{ id: 'nska' }, { id: 'nsty' }, { id: 'nsty' }, { id: 'nwlt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'ndqn' }, { id: 'ndqn' }, { id: 'ndqv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkog' }],
    [{ id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfre', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nfrl' }, { id: 'nfrs' }],
    [{ id: 'ndtb' }, { id: 'ndtb' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nkot' }],
    [{ id: 'ngnw' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nspg' }, { id: 'nspr' }],
  ],
  'Sunken Ruins': [
    [{ id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrl' }, { id: 'nmrr' }],
    [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrt' }, { id: 'ntrt' }],
    [{ id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nmrr' }, { id: 'nmrr' }],
    [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nsgn' }],
    [{ id: 'nsko', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsra' }, { id: 'nsrh' }],
    [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrt' }, { id: 'ntrt' }],
    [{ id: 'nmbg' }, { id: 'nmsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmtw' }, { id: 'nmtw' }],
    [{ id: 'ngnb' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw' }],
    [{ id: 'nggm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngrk' }, { id: 'nsgh' }, { id: 'nsgh' }],
    [{ id: 'nele' }, { id: 'nele' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nrel' }, { id: 'nrel' }],
    [{ id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nmsn' }, { id: 'nmsn' }],
    [{ id: 'nfsh' }, { id: 'nftr' }, { id: 'nftt' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }],
  ],
  'Village': [
    [{ id: 'nftr' }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nhyh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }],
    [{ id: 'nftr' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nvdw' }, { id: 'nwiz' }],
    [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }],
    [{ id: 'nfsh' }, { id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }],
    [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmrr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrel' }, { id: 'nrel' }],
    [{ id: 'nftb' }, { id: 'nftr' }, { id: 'nkog' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nkob' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'nftb' }, { id: 'nftt' }, { id: 'ngno' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }],
    [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogr' }],
    [{ id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrm' }, { id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'ngna' }, { id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }],
    [{ id: 'nban' }, { id: 'nban' }, { id: 'nbrg' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'nele' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwiz' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzr' }],
    [{ id: 'nele' }, { id: 'nele' }, { id: 'nltc' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }],
  ],
  'Village Fall': [
    [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }],
    [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwwf' }, { id: 'nwwf' }],
    [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }],
    [{ id: 'nska' }, { id: 'nskg' }, { id: 'nslf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }],
    [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwwd' }, { id: 'nwwd' }],
    [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nwwf' }],
    [{ id: 'nenf' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }],
    [{ id: 'nkog' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nkot' }],
    [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nwiz' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }],
    [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nsqt' }],
    [{ id: 'ngns' }, { id: 'ngnv' }, { id: 'ngnw' }, { id: 'nowe', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }],
  ],
};
