/** Creep camp data extracted from WC3 1v1 Ladder Maps. */
export const CREEP_CAMPS: Record<string, Record<number, string[][]>> = {
  'Dalaran Ruins': {
    1: [
      ['nkob', 'nkog', 'nkot'],
    ],
    2: [
      ['nfsh', 'nftk', 'nftt', 'nftt'],
      ['nmrl', 'nmrr', 'ntrs', 'ntrt'],
      ['nass', 'ngst', 'nogr', 'nogr', 'nwzr'],
    ],
    3: [
      ['nbrg', 'nrog', 'nwzr'],
      ['nftr', 'nogr', 'nwzg'],
      ['nfsh', 'nftt', 'nftt', 'nsqt'],
      ['nftb', 'nftb', 'nogm', 'nomg'],
      ['nfsh', 'nftb', 'nftb', 'nogl', 'nomg'],
    ],
  },
  'Lordaeron Summer': {
    1: [
      ['ngna', 'ngna', 'ngnb'],
      ['nkob', 'nkog', 'nkot'],
      ['nmrl', 'nmrr', 'nmrr', 'nsc2'],
    ],
    2: [
      ['nfsh', 'nftr', 'nftt'],
      ['nfsh', 'nftt', 'nomg'],
      ['nftb', 'nftb', 'nogm'],
      ['ntrg', 'ntrt', 'ntrt'],
      ['nfsh', 'nftb', 'nogm', 'nomg'],
      ['nfsh', 'nftt', 'ngrk', 'ngst'],
      ['nftt', 'nftt', 'nogr', 'nogr', 'nomg'],
    ],
    3: [
      ['nftb', 'nftt', 'nogr'],
      ['nftr', 'ngna', 'ngnb'],
      ['nftt', 'nftt', 'nogr'],
      ['nftt', 'nftt', 'nomg'],
      ['ngns', 'ngnv', 'ngnw'],
      ['ntrh', 'ntrh', 'ntrt'],
      ['ntrs', 'ntrs', 'ntrt'],
      ['nftr', 'nftr', 'nogr', 'nogr'],
      ['nmrl', 'nmrm', 'nmrr', 'nmrr'],
      ['nsc3', 'nscb', 'ntrt', 'ntrt'],
      ['nfsh', 'nftb', 'nftb', 'nogl', 'nomg'],
      ['nfsh', 'nftr', 'nftr', 'ngrk', 'ngst'],
      ['nfsh', 'nftt', 'nftt', 'ngrk', 'ngst'],
      ['nfsh', 'nftt', 'nftt', 'nogl', 'nomg'],
      ['nftk', 'nftt', 'nftt', 'nogr', 'nogr'],
      ['ngno', 'ngns', 'ngns', 'ngnv', 'ngnw'],
      ['nmfs', 'nmrm', 'nmrm', 'nmrr', 'nmrr'],
      ['nmrm', 'nmrm', 'nmrr', 'nmrr', 'ntrg'],
      ['nmrr', 'nmrr', 'ntrg', 'ntrt', 'ntrt'],
      ['nfsh', 'nftb', 'nftb', 'nogr', 'nomg', 'nrdr'],
      ['nftb', 'nftb', 'nogl', 'nogr', 'nogr', 'nomg'],
      ['nkob', 'nkob', 'nkog', 'nkot', 'nkot', 'nwzg'],
    ],
  },
  'Lordaeron Winter': {
    2: [
      ['nfrs', 'nwlt', 'nwlt'],
      ['nomg', 'ntkt', 'ntkw'],
      ['nftb', 'nitt', 'nomg', 'nplb'],
      ['nmfs', 'nmrl', 'nmrl', 'nmrr'],
      ['nith', 'nitr', 'nitr', 'nits', 'nitw'],
    ],
    3: [
      ['nftt', 'ngnb'],
      ['nmfs', 'nmrr'],
      ['nfpt', 'ntks', 'ntks'],
      ['nfpt', 'ntks', 'ntkt'],
      ['ngna', 'ngnw', 'nwlt'],
      ['ngnw', 'nitr', 'nogr'],
      ['nmam', 'ntka', 'ntkt'],
      ['nfps', 'nmgr', 'nogr', 'nomg'],
      ['nfrb', 'nfrl', 'nfsh', 'nftb'],
      ['nfsh', 'nitt', 'nsqt', 'nwwf'],
      ['nith', 'nits', 'nmgr', 'nplg'],
      ['nitp', 'nitr', 'nomg', 'ntkt'],
      ['nitp', 'nitt', 'nitt', 'nsqt'],
      ['nanb', 'nanc', 'nano', 'nanw', 'nnwl'],
      ['ngnb', 'ngnb', 'ngns', 'ngnv', 'ngnw'],
    ],
  },
  'Northrend': {
    1: [
      ['nsts', 'nwlt', 'nwlt'],
    ],
    2: [
      ['ndtt', 'nogm', 'nspb', 'nspg'],
      ['ngnw', 'nogm', 'nomg', 'nspg', 'nspr'],
      ['ndtb', 'ndtb', 'ngrk', 'ngst', 'nkot'],
    ],
    3: [
      ['nmrr', 'nmtw', 'nsel'],
      ['ndqn', 'ndqn', 'ndqv', 'nkog'],
      ['ndtb', 'ndtt', 'nfrb', 'nfrl'],
      ['ndth', 'ndtr', 'ndtr', 'nsqt'],
      ['nfrb', 'nfre', 'nfrl', 'nfrs'],
      ['nska', 'nsty', 'nsty', 'nwlt'],
    ],
  },
  'Sunken Ruins': {
    1: [
      ['nmrm', 'nmrr', 'nmrr'],
      ['nsko', 'nsra', 'nsrh'],
    ],
    2: [
      ['nlsn', 'ntrt', 'ntrt'],
      ['ntrg', 'ntrt', 'ntrt'],
      ['nele', 'nele', 'nomg', 'nrel', 'nrel'],
      ['nmrm', 'nmrm', 'nmrv', 'nmsn', 'nmsn'],
    ],
    3: [
      ['ntrs', 'ntrt'],
      ['nftb', 'nftt', 'nsgn'],
      ['nmfs', 'nmrl', 'nmrr'],
      ['nggm', 'ngrk', 'nsgh', 'nsgh'],
      ['ngnb', 'ngns', 'ngnv', 'ngnw'],
      ['nmbg', 'nmsn', 'nmtw', 'nmtw'],
      ['nfsh', 'nftr', 'nftt', 'ngrk', 'ngst'],
    ],
  },
  'Village': {
    1: [
      ['nftr', 'nftt'],
      ['nban', 'nban', 'nbrg', 'nbrg', 'nrog'],
    ],
    2: [
      ['nban', 'nbrg', 'nrog', 'nwzg'],
      ['nfsh', 'nfsp', 'nftb', 'nogm'],
      ['nftb', 'nftt', 'nkob', 'nkol'],
      ['nftk', 'nftt', 'nftt', 'nogr'],
      ['nele', 'nele', 'nltc', 'ntrg', 'ntrt'],
    ],
    3: [
      ['nhyh', 'ntrt'],
      ['nenf', 'nvdw', 'nwiz'],
      ['nftr', 'ngnb', 'ngnw'],
      ['nmrl', 'nmrm', 'nmrr'],
      ['nfsh', 'nftb', 'nogr', 'nomg'],
      ['nfsp', 'nftb', 'nftt', 'nogr'],
      ['nftb', 'nftr', 'nkog', 'nsqt'],
      ['nftb', 'nftt', 'ngno', 'ngst'],
      ['nlsn', 'nmrr', 'nrel', 'nrel'],
      ['nele', 'nenf', 'nwiz', 'nwzd', 'nwzr'],
      ['ngna', 'ngnb', 'ngnb', 'ngnv', 'ngnw'],
      ['nmrm', 'nmrm', 'ntrh', 'ntrh', 'ntrt'],
    ],
  },
  'Village Fall': {
    1: [
      ['ngnw', 'nwwf', 'nwwf'],
    ],
    2: [
      ['nenf', 'ngns', 'ngnv'],
      ['nbrg', 'nbrg', 'nwiz', 'nwzr'],
      ['nfsh', 'nftb', 'nftk', 'nsqt'],
    ],
    3: [
      ['nftt', 'nftt', 'nomg'],
      ['nftb', 'nftt', 'nsqt'],
      ['nftb', 'nftt', 'nwwf'],
      ['nggr', 'nwwd', 'nwwd'],
      ['nska', 'nskg', 'nslf'],
      ['nkog', 'nkog', 'nkol', 'nkot'],
      ['ngns', 'ngnv', 'ngnw', 'nowe'],
    ],
  },
};
