/** An item drop from a creep. */
export interface ItemDrop {
  type: itemtype;
  level: number;
}

/** A creep in a camp, with optional item drops. */
export interface CreepUnit {
  id: string;
  itemDrops?: ItemDrop[];
}

/** A single creep camp composition.
 *  `level` is the WC3 ladder minimap dot classification — the SUM of the
 *  creep levels in the camp: 1-9 = green (1), 10-19 = orange (2), 20+ =
 *  red (3). Precomputed from the standard game data; if camp compositions
 *  change, recompute (sum each creep's unit level and apply the thresholds).
 *  Level 2 camps enter the random selection once the Mercenary Contract is
 *  purchased; level 3 never rolls. */
export interface CreepCamp {
  level: number;
  /** The ladder-map tileset this camp was taken from. Reference only -- nothing
   *  reads it, and camps are never filtered by it. */
  tileset: string;
  creeps: CreepUnit[];
}

/** Every creep camp we know of, as one flat list.
 *
 *  Extracted from the W3Champions ladder maps -- 1v1, 2v2, 3v3, 4v4 and FFA --
 *  by tools/extract_creeps.js, which reads each map's war3map.lua for creep
 *  positions and item-drop triggers and clusters them into camps.
 *
 *  `tileset` is recorded for reference only. The game does not read it: a camp
 *  is chosen on level alone, and the terrain it originally stood on has no
 *  bearing on how it plays here. */
export const CREEP_CAMPS: CreepCamp[] = [
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nfrl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfrs' }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nftr' }, { id: 'nftt' }, { id: 'nmsh', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nska' }, { id: 'nska' }, { id: 'uktn' }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnb' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Ashenvale', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkot' }] },
  { level: 1, tileset: 'Barrens', creeps: [{ id: 'ncea' }, { id: 'ncer', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nele', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nrog' }, { id: 'nrog' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nhdc', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nhfp' }, { id: 'nhfp' }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nkog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nrog' }, { id: 'nrog' }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nrog' }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwlt' }, { id: 'nwlt' }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nban' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Cityscape', creeps: [{ id: 'nban' }, { id: 'nrog' }, { id: 'nwiz' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'nskg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'nele', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nsel', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftr' }, { id: 'nrog' }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'ngrk' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkot', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nwiz' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Dalaran', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'ngrk' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwzr' }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkot' }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nmrl' }, { id: 'nmrr' }, { id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nhdc' }, { id: 'nhfp' }, { id: 'nsln', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfsp' }, { id: 'nkog' }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nskg' }, { id: 'nskg' }] },
  { level: 1, tileset: 'Dalaran Ruins', creeps: [{ id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Fall', creeps: [{ id: 'ntkf' }, { id: 'ntkf' }, { id: 'ntks', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Fall', creeps: [{ id: 'nits', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwwf' }, { id: 'nwwf' }] },
  { level: 1, tileset: 'Lordaeron Fall', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkot' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ntrs' }, { id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nftr' }, { id: 'nftt' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrr' }, { id: 'nmrr' }, { id: 'nsc2', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngno' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwlt' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftr' }, { id: 'nftr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftr' }, { id: 'nogr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngno' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nspg' }, { id: 'nspg' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ndmu' }, { id: 'ndmu' }, { id: 'nsko', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkot', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nban' }, { id: 'nsel', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nlds', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nlpd' }, { id: 'nlpd' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nftr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngno' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngnb' }, { id: 'ngno' }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngno' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ngnw' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'ngnw' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngnb' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ngnw' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmrm' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrr' }, { id: 'nmrr' }, { id: 'nsc2', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nscb' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngno' }, { id: 'ngno' }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nspb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nspb' }, { id: 'nspg' }, { id: 'nspg' }, { id: 'nspg' }] },
  { level: 1, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'nspb' }, { id: 'nspg' }, { id: 'nspg' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nftt' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfrs', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nwlt' }, { id: 'nwlt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngna' }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwlt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmam', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ntka' }, { id: 'ntkt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngnw' }, { id: 'nitr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfpl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nitt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nitr' }, { id: 'nitt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'ntka' }, { id: 'ntkf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntkh', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nitr' }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nitr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'narg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwiz' }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nitr' }, { id: 'nitt' }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'nbrg' }, { id: 'nkot' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngno' }, { id: 'ngno' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Northrend', creeps: [{ id: 'nsts', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwlt' }, { id: 'nwlt' }] },
  { level: 1, tileset: 'Northrend', creeps: [{ id: 'nska' }, { id: 'nsty' }, { id: 'nsty' }, { id: 'nwlt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Northrend', creeps: [{ id: 'nitt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nwwf' }, { id: 'nwwf' }, { id: 'nwwf' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'ntrs' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrl' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nsko', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsra' }, { id: 'nsrh' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmtw' }, { id: 'nmtw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nftr' }, { id: 'njg1', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nsko', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nsko' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmcf' }, { id: 'nmsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmtw' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmbg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrh' }, { id: 'ntrh' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmrr' }, { id: 'nmtw' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nhyh', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmcf' }, { id: 'nmcf' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nmcf' }, { id: 'nmcf' }, { id: 'nmtw' }, { id: 'ntrs', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ntrs' }] },
  { level: 1, tileset: 'Sunken Ruins', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nhfp' }, { id: 'nhfp' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nftr' }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nhyh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nftr' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nvdw' }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nbrg' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwiz' }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngno' }, { id: 'ngno' }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nban' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwiz' }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 1, tileset: 'Village', creeps: [{ id: 'nsgt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nspg' }, { id: 'nspg' }, { id: 'nspg' }] },
  { level: 1, tileset: 'Village Fall', creeps: [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwwf' }, { id: 'nwwf' }] },
  { level: 1, tileset: 'Village Fall', creeps: [{ id: 'nska' }, { id: 'nskg' }, { id: 'nslf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 1, tileset: 'Village Fall', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nwwf' }] },
  { level: 1, tileset: 'Village Fall', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nwiz' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 1, tileset: 'Village Fall', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nbda' }, { id: 'nbdm' }, { id: 'nbdw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nwlg' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nfov', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nskm' }, { id: 'nskm' }, { id: 'nsko' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nbda' }, { id: 'nbdm' }, { id: 'ntkc', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ntks' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nfrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nfrl' }, { id: 'nfrs' }, { id: 'nfrs' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nftb' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nmrr' }, { id: 'nmrr' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmtw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nftr' }, { id: 'nsqo', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nwlt' }, { id: 'nwlt' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkob' }, { id: 'nkob' }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nwlg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwlt' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Ashenvale', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngna' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Barrens', creeps: [{ id: 'ncim', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nowb' }, { id: 'nowb' }] },
  { level: 2, tileset: 'Barrens', creeps: [{ id: 'ncea' }, { id: 'ncea' }, { id: 'ncen' }, { id: 'ncen' }, { id: 'ncks', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Barrens', creeps: [{ id: 'ncea' }, { id: 'ncea' }, { id: 'ncks', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrzb' }, { id: 'nrzb' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nplb' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nhfp' }, { id: 'nplb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrog' }, { id: 'nrog' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nkog' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'narg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nbrg' }, { id: 'nbrg' }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'narg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'narg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nrog' }, { id: 'nwiz' }, { id: 'nwiz' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nhfp' }, { id: 'nhfp' }, { id: 'nhhr' }, { id: 'nhhr' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nfsp' }, { id: 'nftr' }, { id: 'nftr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nhhr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkob' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nbrg' }, { id: 'nplg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwiz' }, { id: 'nwiz' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nkot' }, { id: 'nkot' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nban' }, { id: 'nban' }, { id: 'nban' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nban' }, { id: 'nban' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzr' }, { id: 'nwzr' }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nrog' }, { id: 'nrog' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Cityscape', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkog' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nele' }, { id: 'nele' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'narg' }, { id: 'narg' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nass' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nrog' }, { id: 'nwzr' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'ndth', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ndtr' }, { id: 'nftb' }, { id: 'nmgw', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nplb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntka' }, { id: 'ntkt' }, { id: 'ntkt' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nogr' }, { id: 'nogr' }, { id: 'nsrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nass', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nban' }, { id: 'nbrg' }, { id: 'nenf' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftr' }, { id: 'nftr' }, { id: 'nwlt' }, { id: 'nwlt' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'narg' }, { id: 'narg' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nftt' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nkob' }, { id: 'nkog' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nrel' }, { id: 'nrel' }, { id: 'nsko', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nsra' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nhfp' }, { id: 'nhfp' }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'ndtr' }, { id: 'ndtr' }, { id: 'nwlg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwlt' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran', creeps: [{ id: 'ndrf' }, { id: 'ndrw' }, { id: 'ndtw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nvdw' }, { id: 'nvdw' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nftr' }, { id: 'nogr' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nomg' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nftt' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nass' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzg' }, { id: 'nwzg' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nbda' }, { id: 'nbda' }, { id: 'ntks', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkog' }, { id: 'nkot' }, { id: 'nsqe', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'narg' }, { id: 'nele' }, { id: 'nele' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngnw' }, { id: 'ngrk' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'ndrp' }, { id: 'ndrp' }, { id: 'ndrs' }, { id: 'npfm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nskg' }, { id: 'nskg' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'ndqn' }, { id: 'ndqn' }, { id: 'nsrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsrn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nndk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nomg' }, { id: 'nskf' }, { id: 'nskf' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nrvl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nskf' }, { id: 'nskf' }, { id: 'nwzg' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsp' }, { id: 'nftt' }, { id: 'nkob' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nrog' }] },
  { level: 2, tileset: 'Dalaran Ruins', creeps: [{ id: 'nass', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nban' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nhdc' }, { id: 'nrog' }] },
  { level: 2, tileset: 'Lordaeron Fall', creeps: [{ id: 'nftt' }, { id: 'nrog' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Fall', creeps: [{ id: 'nfpl', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nitt' }, { id: 'nitt' }] },
  { level: 2, tileset: 'Lordaeron Fall', creeps: [{ id: 'nitt' }, { id: 'nitt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Fall', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nits' }, { id: 'nitw', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nspb' }, { id: 'nspb' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nsc3', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nscb' }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'nftr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nogm' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrm' }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrr' }, { id: 'nmrr' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftr' }, { id: 'nftr' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngno' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrr' }, { id: 'nmrr' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkog' }, { id: 'nkot' }, { id: 'nkot' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nenf' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'ngns' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'njg1' }, { id: 'njga' }, { id: 'njgb', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nowe', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nqbh' }, { id: 'nqbh' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nwld', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nwlt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nwlt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'nftt' }, { id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngns' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ndtp' }, { id: 'ndtt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nfrl', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfrs' }, { id: 'nfrs' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nwlt' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfpl', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfps' }, { id: 'nfps' }, { id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nenp' }, { id: 'nfsp' }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwiz' }, { id: 'nwzr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngrk' }, { id: 'ngrk' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmrm' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngns' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nwlg' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftr' }, { id: 'njg1' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrs' }, { id: 'ntrs' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nmrr' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftr' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftr' }, { id: 'nftr' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nlds', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nlkl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nlpd' }, { id: 'nlpr' }, { id: 'nltc' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nrdk' }, { id: 'nrdk', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngnb' }, { id: 'ngno' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'ngnw' }, { id: 'nmrm' }, { id: 'nmrr' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftr' }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngrk' }, { id: 'ngrk' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'nftr' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngno' }, { id: 'ngno' }, { id: 'ngns' }, { id: 'ngns' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnw' }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Summer', creeps: [{ id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntks' }, { id: 'ntkt' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntks' }, { id: 'ntks' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntkt' }, { id: 'ntkw' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfsh' }, { id: 'nitt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nwwf' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nfrl' }, { id: 'nfsh' }, { id: 'nftb' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nitt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nitt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nftb' }, { id: 'nitt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nplb' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nitr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntkt' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nanb' }, { id: 'nanc' }, { id: 'nano', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nanw' }, { id: 'nnwl', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith' }, { id: 'nitr' }, { id: 'nitr' }, { id: 'nits' }, { id: 'nitw', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith' }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwwd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmrm' }, { id: 'nmrm' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nbdw', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ndrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nitr' }, { id: 'nitt' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ndrd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ndrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndrp' }, { id: 'ndrw' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ndrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndrm' }, { id: 'ndrp' }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nitt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngrk' }, { id: 'nits' }, { id: 'nitt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }, { type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nkog' }, { id: 'nrog' }, { id: 'nrog' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nass', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nban' }, { id: 'nrog' }, { id: 'nrog' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nits' }, { id: 'nwlg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nwwf' }, { id: 'nwwf' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nass', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nbrg' }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngno' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nhdc' }, { id: 'nhdc' }, { id: 'nwrg' }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'narg' }, { id: 'narg' }, { id: 'nhdc' }, { id: 'nhdc' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nkog' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nits', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nitt' }, { id: 'nitt' }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngnb' }, { id: 'ngnw' }, { id: 'ngnw' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nitp' }, { id: 'nitt' }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nitt' }, { id: 'nitt' }, { id: 'nrvs' }, { id: 'nrvs' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 2, tileset: 'Lordaeron Winter', creeps: [{ id: 'nhfp' }, { id: 'nhfp' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nmrr' }, { id: 'nmtw' }, { id: 'nsel', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ndth', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndtr' }, { id: 'ndtr' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ndtt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nspb' }, { id: 'nspg' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ndtb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ndtt' }, { id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nfrl' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ndqn' }, { id: 'ndqn' }, { id: 'ndqv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkog' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ndtb' }, { id: 'ndtb' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'ngnw' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nspg' }, { id: 'nspr' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nfrp', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nfrp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntkh' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nith' }, { id: 'nwna', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwnr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nitr' }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwen', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nwen' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nfrp' }, { id: 'nfrp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntka' }, { id: 'ntks', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nitp' }, { id: 'nitt' }, { id: 'nwen', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nitr' }, { id: 'nitt' }, { id: 'nitt' }, { id: 'nnwa' }, { id: 'nnws', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nith' }, { id: 'nnwa' }, { id: 'nnwa' }, { id: 'nnwq', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nspd' }] },
  { level: 2, tileset: 'Northrend', creeps: [{ id: 'nith' }, { id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nitr' }, { id: 'nitr' }, { id: 'nitw', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nsgn' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmbg' }, { id: 'nmsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmtw' }, { id: 'nmtw' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'ngnb' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nele' }, { id: 'nele' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nrel' }, { id: 'nrel' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nfsh' }, { id: 'nftr' }, { id: 'nftt' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmsn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmtw' }, { id: 'nmtw' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nsoc', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nsog' }, { id: 'nsog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nsgh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsgn' }, { id: 'nsgn' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'ndrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrv' }, { id: 'ntrv' }, { id: 'ntrv' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrel' }, { id: 'nrel' }, { id: 'nrel' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlpd' }, { id: 'nlpd' }, { id: 'nlpd' }, { id: 'nsel', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nfsp' }, { id: 'nftb' }, { id: 'njg1' }, { id: 'njga', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nsrh' }, { id: 'nsrh' }, { id: 'nsrh' }, { id: 'nsrn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlds', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nlpd' }, { id: 'nlpd' }, { id: 'nlpr' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrh' }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmsn' }, { id: 'nmtw' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ntrh' }, { id: 'ntrt' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlpd' }, { id: 'nlpd' }, { id: 'nsgh', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nsgn' }, { id: 'nsgn' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmsn' }, { id: 'nmsn', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nfsp' }, { id: 'nftb' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nftt' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nlpd' }, { id: 'nlpd' }, { id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nrel', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrel' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nkob' }, { id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmcf' }, { id: 'nmcf' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nmsn' }, { id: 'nmtw' }, { id: 'nmtw' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmbg' }, { id: 'nmbg' }, { id: 'nmcf' }, { id: 'nmcf' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmsn' }] },
  { level: 2, tileset: 'Sunken Ruins', creeps: [{ id: 'nmfs', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrl' }, { id: 'nmrl' }, { id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nmrr' }, { id: 'nmrr' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nban' }, { id: 'nbrg' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsh' }, { id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftt' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nlsn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nmrr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrel' }, { id: 'nrel' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftb' }, { id: 'nftr' }, { id: 'nkog' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nkob' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'ngno' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogr' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nmrm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nmrm' }, { id: 'ntrh' }, { id: 'ntrh' }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'ngna' }, { id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftt' }, { id: 'nftt' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkot' }, { id: 'nkot' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nrog' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nkog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'ngno' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nwzg' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nass' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrog' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nftr' }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsp' }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsp' }, { id: 'nftt' }, { id: 'nsqo', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nsqt' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nenc' }, { id: 'nenc' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nftt' }, { id: 'nwlg' }, { id: 'nwlg' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'ngno', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngns' }, { id: 'ngns' }, { id: 'ngnv' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsh' }, { id: 'nftr' }, { id: 'nwld', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwlg' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftr' }, { id: 'nftr' }, { id: 'nftr' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nbrg' }, { id: 'nbrg' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nenf' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngnw' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nfsp' }, { id: 'nfsp', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nftr' }, { id: 'nftr' }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nrog' }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nrog', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Village', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nban' }, { id: 'nban' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nenf' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nkog' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'nkot' }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nsqt' }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'ngns' }, { id: 'ngnv' }, { id: 'ngnw' }, { id: 'nowe', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nwzr' }, { id: 'nwzr' }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nfsp' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nsqt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_PERMANENT, level: 1 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nban' }, { id: 'nban' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nrog' }, { id: 'nrog' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 2, tileset: 'Village Fall', creeps: [{ id: 'nkob' }, { id: 'nkob' }, { id: 'nkob' }, { id: 'nkog' }, { id: 'nkog' }, { id: 'nkol', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Ashenvale', creeps: [{ id: 'nfpt' }, { id: 'nfpt' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }] },
  { level: 3, tileset: 'Ashenvale', creeps: [{ id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngst' }, { id: 'nowk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }] },
  { level: 3, tileset: 'Ashenvale', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nba2', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nfov', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Ashenvale', creeps: [{ id: 'nftb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftb' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nkog' }] },
  { level: 3, tileset: 'Ashenvale', creeps: [{ id: 'nass' }, { id: 'nbld', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nrog' }, { id: 'nrog' }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Barrens', creeps: [{ id: 'ncer' }, { id: 'ncim' }, { id: 'ncim' }, { id: 'ncks' }, { id: 'nowe', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Barrens', creeps: [{ id: 'nhrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nhrw' }, { id: 'nhrw' }, { id: 'nrzb' }, { id: 'nrzb' }, { id: 'nrzg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nkog' }, { id: 'nkog' }, { id: 'nkot' }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nbld', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngh1' }, { id: 'nrog' }, { id: 'nrvl', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nkob' }, { id: 'nkol' }, { id: 'nrog' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nggr' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngrk' }, { id: 'ngrk' }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nkog' }, { id: 'nkog' }, { id: 'nsgg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nrdk' }, { id: 'nrdk' }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nogm' }, { id: 'nogm' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwiz' }, { id: 'nwzr' }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nrog' }, { id: 'nrog' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzr' }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nban' }, { id: 'nban' }, { id: 'nele' }, { id: 'nele' }, { id: 'nhdc' }, { id: 'nhdc' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nhdc' }, { id: 'nhdc' }, { id: 'nrog' }, { id: 'nrog' }, { id: 'nsgg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Cityscape', creeps: [{ id: 'nrog' }, { id: 'nrog' }, { id: 'nrog' }, { id: 'nrog' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwiz' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }, { type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nwzr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nltl' }, { id: 'nsc3' }, { id: 'nsc3', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'narg' }, { id: 'narg' }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nsgg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'nomg' }, { id: 'nrvi', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nskf' }, { id: 'nskf' }, { id: 'nwrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'nass' }, { id: 'nfov', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nhdc' }, { id: 'nhhr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrog' }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'nsrv', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsrv', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nvdg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'nvdw' }, { id: 'nvdw' }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'nass' }, { id: 'nbrg' }, { id: 'nrvi', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'ndrh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ndrw' }, { id: 'nndr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nnht' }, { id: 'nnht' }] },
  { level: 3, tileset: 'Dalaran', creeps: [{ id: 'ngnw' }, { id: 'ngnw' }, { id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwlg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwlg' }] },
  { level: 3, tileset: 'Dalaran Ruins', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg' }] },
  { level: 3, tileset: 'Dalaran Ruins', creeps: [{ id: 'nhdc' }, { id: 'nhdc' }, { id: 'nndr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzg' }] },
  { level: 3, tileset: 'Dalaran Ruins', creeps: [{ id: 'nass' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nsqo', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsqt' }] },
  { level: 3, tileset: 'Dalaran Ruins', creeps: [{ id: 'nbal' }, { id: 'nfel' }, { id: 'nfel' }, { id: 'nlrv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nskf' }, { id: 'nskf' }] },
  { level: 3, tileset: 'Lordaeron Fall', creeps: [{ id: 'nfrp' }, { id: 'nfrp' }, { id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nits' }, { id: 'nwns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftt' }, { id: 'nftt' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nomg' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nftb' }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ntrg' }, { id: 'ntrg' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nbwm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nsqo', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nsqt' }, { id: 'nsqt' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }, { id: 'ntrt' }, { id: 'ntrt' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngst' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'nftt' }, { id: 'nrzb' }, { id: 'nrzg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 5 }] }, { id: 'nrzm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nbrg' }, { id: 'nenf' }, { id: 'nrog' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 2 }] }, { id: 'nrwm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'ndtt' }, { id: 'ndtt' }, { id: 'nwlg' }, { id: 'nwlg' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nemi' }, { id: 'nenf' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nrog' }, { id: 'nwzg' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'ndtb' }, { id: 'ndtb' }, { id: 'nhrq', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nsgt' }, { id: 'nsgt' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftb' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 3 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrwm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }, { type: ITEM_TYPE_PERMANENT, level: 6 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh' }, { id: 'nftb' }, { id: 'nogl' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 5 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftt' }, { id: 'nftt' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftr' }, { id: 'nftr' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }] }, { id: 'nrdr' }, { id: 'nrdr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nass' }, { id: 'nbdk', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nbrg' }, { id: 'nelb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nenf' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nftb' }, { id: 'nftt' }, { id: 'nggr', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrdk' }, { id: 'nrdk' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nfsh', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nftb' }, { id: 'nftk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nogm' }, { id: 'nomg' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'nass' }, { id: 'nass' }, { id: 'nbld', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nrog' }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Lordaeron Summer', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngns' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'ngnw' }, { id: 'ngnw' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith' }, { id: 'nits' }, { id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nplg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfps' }, { id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nadr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nbdw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nbdw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngns' }, { id: 'ngnw' }, { id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwwd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nfps' }, { id: 'nfps' }, { id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nfpt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nfpu', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngns' }, { id: 'ngnw' }, { id: 'nith', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nits', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwns', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nkog' }, { id: 'nkot' }, { id: 'nkot' }, { id: 'nsgg', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nith' }, { id: 'nith' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nomg' }, { id: 'nomg' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nbld', itemDrops: [{ type: ITEM_TYPE_ARTIFACT, level: 7 }] }, { id: 'nenf' }, { id: 'nenf' }, { id: 'nhhr' }, { id: 'nhhr' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nbdk', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nith' }, { id: 'nitt' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nogr' }, { id: 'nogr' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nits' }, { id: 'nits' }, { id: 'nogl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogm' }, { id: 'nogm' }, { id: 'nomg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nmpg' }, { id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrm' }, { id: 'nrvi' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'ntkc', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ntks' }, { id: 'ntkt' }, { id: 'ntkt' }, { id: 'ntkw' }, { id: 'nwwf' }, { id: 'nwwf' }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'nitp' }, { id: 'nitp' }, { id: 'nitt' }, { id: 'nitt' }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nogm', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 3 }] }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nogr', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }] },
  { level: 3, tileset: 'Lordaeron Winter', creeps: [{ id: 'ngna' }, { id: 'ngna' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngnw' }, { id: 'ngnw' }, { id: 'nitt' }, { id: 'nitt' }, { id: 'nitw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Northrend', creeps: [{ id: 'nfrb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nfre', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nfrl' }, { id: 'nfrs' }] },
  { level: 3, tileset: 'Northrend', creeps: [{ id: 'nith' }, { id: 'nitt' }, { id: 'nwna', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwnr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }] },
  { level: 3, tileset: 'Northrend', creeps: [{ id: 'nmgr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ntka' }, { id: 'ntkh' }, { id: 'ntks', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ntkt' }] },
  { level: 3, tileset: 'Northrend', creeps: [{ id: 'nadk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 1 }] }, { id: 'nfpc', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }] }, { id: 'nfpe', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 6 }] }, { id: 'nfps' }, { id: 'nfps' }, { id: 'nitt' }, { id: 'nitt' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nggm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngrk' }, { id: 'nsgh' }, { id: 'nsgh' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nmrm' }, { id: 'nmrm' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'nmsn' }, { id: 'nmsn' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nahy', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nehy' }, { id: 'nhyh' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ntrt' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nlds', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nlds' }, { id: 'nlkl', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nlsn' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nftb' }, { id: 'nftr' }, { id: 'nftt' }, { id: 'ngdk', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'njgb', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nggm', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngrk' }, { id: 'ngrk' }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngst' }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nsko' }, { id: 'nsog', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nsrh' }, { id: 'nsrh' }, { id: 'nsrn', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 3, tileset: 'Sunken Ruins', creeps: [{ id: 'nelb', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nele' }, { id: 'nele' }, { id: 'nsrh' }, { id: 'nsrh' }, { id: 'nsrw', itemDrops: [{ type: ITEM_TYPE_ARTIFACT, level: 8 }] }, { id: 'ntrv' }, { id: 'ntrv' }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nele' }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwiz' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nele' }, { id: 'nele' }, { id: 'nltc' }, { id: 'ntrg', itemDrops: [{ type: ITEM_TYPE_CHARGED, level: 4 }] }, { id: 'ntrt', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngst', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'ngst' }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nenf' }, { id: 'nrog' }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzg', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nenf', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nwzd', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwzr' }, { id: 'nwzr' }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nmrm' }, { id: 'nmrr' }, { id: 'nmrr' }, { id: 'nmrv', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }, { id: 'nmsc', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 4 }] }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'nfsh' }, { id: 'nftt' }, { id: 'ngdk', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 2 }] }, { id: 'nsqa', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 6 }, { type: ITEM_TYPE_POWERUP, level: 1 }, { type: ITEM_TYPE_POWERUP, level: 1 }] }, { id: 'nsqe' }] },
  { level: 3, tileset: 'Village', creeps: [{ id: 'ngnb' }, { id: 'ngnb' }, { id: 'ngns' }, { id: 'ngns' }, { id: 'ngnv', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'ngnw', itemDrops: [{ type: ITEM_TYPE_POWERUP, level: 2 }] }] },
  { level: 3, tileset: 'Village Fall', creeps: [{ id: 'nggr', itemDrops: [{ type: ITEM_TYPE_PERMANENT, level: 5 }] }, { id: 'nwwd' }, { id: 'nwwd' }] },
];
